image: node:14

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  script:
    - npm install
    - npm run build

run_tests:
  stage: test
  script:
    - npm run test
  only:
    - branches

deploy_prod:
  stage: deploy
  script:
    - npm run start:prod
  environment:
    name: Production
  only:
    - main
  dependencies:
    - build_app
    - run_tests

variables:
  MONGO_URI: "$MONGO_URI"
