image: node:14

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  script:
    - npm install --prefix server
    - npm run build --prefix server

run_tests:
  stage: test
  script:
    - npm install jest --prefix server

    - npm run test:e2e  --prefix server

  only:
    - branches

deploy_prod:
  stage: deploy
  script:
    cd server && node dist/main
  environment:
    name: Production
  only:
    - main
  dependencies:
    - build_app
    - run_tests

variables:
  DATABASE_URL: "$DATABASE_URL"
